name: Build, Push and Deploy Node.js app

# アクションを実行するタイミングを制御します。
on:
  # プッシュイベントが発生したときにワークフローを起動するが、その対象は mainブランチのみとする
  push:
    branches: [main]

  # [Actions] タブから手動でワークフローを実行することができます。
  workflow_dispatch:

env:
  # docker-imageをGitHubのパッケージにプッシュ
  REGISTRY: docker.pkg.github.com
  # イメージ名で、これをpushしたりpullしたりする
  REPO: tfarras/nodejs-deploy/nodejs-image
  # コンテナの停止または起動に使用されるコンテナ名
  CONTAINER: nodejs-image

jobs:
  # １番目のジョブ名
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        # 使用するアクションの設定を受け取るブロック
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.REGISTRY }}
          repository: ${{ env.REPO }}
          # ビルドした画像にgitリファレンスのタグを自動的に付けます。(ドキュメントより)
          tag_with_ref: true

  # ２番目のジョブ名
  deploy:
    # 1番目のジョブに依存することを指定する
    needs: [push_to_registry]
    name: Deploy to Conoha
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH connection
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Login to the GitHub Packages Docker Registry
        run: ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "sudo docker login ${{env.REGISTRY}} -u ${{github.actor}} -p ${{secrets.GITHUB_TOKEN}}"

      - name: Pull latest container
        run: |
          ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "docker pull ${{env.REGISTRY}}/${{env.REPO}}:latest"

      - name: Stop deployed container
        continue-on-error: true
        run: |
          ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "docker stop ${{env.CONTAINER}}"

      - name: Remove deployed container
        continue-on-error: true
        run: |
          ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "docker rm ${{env.CONTAINER}}"

      - name: Start docker container
        run: |
          ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "docker run -p 8080:8080 -d --name=${{env.CONTAINER}} ${{env.REGISTRY}}/${{env.REPO}}:latest"

      - name: Logout from the GitHub Packages Docker Registry
        run: ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "docker logout ${{env.REGISTRY}}"
